spring:
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
#    ## Redis服务器地址
#    host: 192.168.31.13
#    ## Redis服务器连接端口
#    port: 6379
    ## Redis服务器连接密码（默认为空）
    password: 123456
    sentinel:
      master: mymaster
      nodes: 192.168.31.13:26379
server:
  port: 8080
  servlet:
    context-path: /master-slave-server