spring:
  ## Redis 配置
  redis:
    password: 123456
    timeout: 5000
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26380
    lettuce:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制） 默认8
        max-active: 500
        ## 连接池中的最小空闲连接 默认0
        min-idle: 0
        ## 连接池中的最大空闲连接 默认8
        max-idle: 500
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1s
#        max-idle: 8
#        min-idle: 0
#  redis:
#    ## Redis数据库索引（默认为0）
#    database: 1
##    ## Redis服务器地址
##    host: 192.168.31.13
##    ## Redis服务器连接端口
##    port: 6379
#    ## Redis服务器连接密码（默认为空）
#    password: 123456
#    sentinel:
#      master: mymaster
#      nodes: 192.168.31.131:26379
server:
  port: 8080
  servlet:
    context-path: /master-slave-server