spring:
  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:

#    # redisson相关配置, 会导致redis原有配置失效，使用时需注意
#    redisson:
#      file: "classpath:redisson-single.yml"

server:
  port: 8080
  servlet:
    context-path: /stand-alone-server